name: Deploy Static Site

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to AWS using OIDC 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::235695894475:role/github-deploy-s3-cloudfront
          aws-region: eu-west-2

      # Upload static files to S3
      - name: Deploy to S3
        run: aws s3 sync landing-page/ s3://bensalem-injury-landing-235695894475-eu-west-2-an --delete
        

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1O0PR6X0NNZZM \
            --paths "/*"